spring:
    profiles:
        active: prod
    application:
        name: greenhouse
    data:
        mongodb:
            uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:27017/greenhouse?authSource=admin
            database: greenhouse

endpoints:
    esp-server:
        url: http://192.168.18.26:8080
        port: 8080
        endpoints:
            dht: /api/dht
            # TODO Finish this endpoint
            gpio: /api/gpio/%s/%d/%d
